#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("AnimationDrawble.Unpause.Issue.Resource", IsApplication=true)]

namespace AnimationDrawble.Unpause.Issue
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int d1 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int d10 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int d2 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int d3 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int d4 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int d5 = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int d6 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int d7 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int d8 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int d9 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int d_animation = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int Icon = 2130837515;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050002
			public const int btn_pause = 2131034114;
			
			// aapt resource value: 0x7f050003
			public const int btn_resume = 2131034115;
			
			// aapt resource value: 0x7f050001
			public const int btn_start = 2131034113;
			
			// aapt resource value: 0x7f050004
			public const int d_animation = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int imgView_animation = 2131034112;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int ApplicationName = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
